[package]
edition = "2021"
name = "game-of-life-rs"
version = "0.1.0"

[dependencies]
env_logger = "0.10"
error-iter = "0.4"
fastrand = "2.0"
log = "0.4"
pixels = "0.13.0"
winit = "0.28"
winit_input_helper = "0.14"
